/* eslint-disable */
export default [
  {
    nodeName: 'NodeNumber',
    key: 'Número',
    inputs: 0,
    outputs: 1,
    options: {},
    data: { type: 'input', value: '0', color: 'success', pythonStr: '' },
    options: {},
    shortcut: 'Control+a',
  },
  {
    nodeName: 'NodeAssign',
    key: 'Asignación',
    inputs: 1,
    outputs: 1,
    options: {},
    data: { type: 'operation', value: '', color: 'dark', pythonStr: '' },
    options: {},
    shortcut: 'Control+s',
  },
  {
    nodeName: 'NodeCodeBlock',
    key: 'Bloque código',
    inputs: 1,
    outputs: 1,
    options: {},
    class: 'node-code',
    data: {
      type: 'bloque',
      value: '',
      color: 'dark',
      pythonStr: '',
    },
    options: {},
    shortcut: 'Control+d',
  },
  {
    nodeName: 'NodeFor',
    key: 'Bloque for',
    inputs: 1,
    outputs: 1,
    options: {},
    class: 'node-code',
    data: {
      type: 'operation',
      valueDesde: '',
      valueHasta: '',
      value: '',
      color: 'dark',
      pythonStr: '',
    },
    options: {},
    shortcut: 'Control+f',
  },
  {
    nodeName: 'NodeIfElse',
    key: 'Bloque if',
    inputs: 1,
    outputs: 1,
    options: {},
    class: 'node-code',
    data: {
      type: 'operation',
      valueIf: '',
      valueElse: '',
      value: '',
      color: 'dark',
      nodeFrom: '',
      valueCompare: '',
      pythonStr: '',
    },
    options: {},
    shortcut: 'Control+z',
  },
  {
    nodeName: 'NodeLess',
    key: 'Substracción',
    inputs: 1,
    outputs: 1,
    options: {},
    data: {
      type: 'operation',
      value: '0',
      color: 'danger',
      pythonStr: '',
    },
    options: {},
    shortcut: 'Control+x',
  },
  {
    nodeName: 'NodeAdd',
    key: 'Sumatoria',
    inputs: 1,
    outputs: 1,
    options: {},
    data: {
      type: 'operation',
      value: '0',
      color: 'warning',
      operation: 'add',
      pythonStr: '',
    },
    shortcut: 'Control+c',
  },
]
