from flask import Flask
import subprocess
import html
from flask_cors import CORS

app = Flask(__name__)
CORS(app)


@app.route("/format")
def hello_world():
    processformat = subprocess.Popen(
        ['autopep8', '--in-place', '--aggressive', '--aggressive', '/usr/src/output/autogenerated.py'], stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, universal_newlines=True)
    stdout, stderr = processformat.communicate()

    if(stderr):
        return {'code': 'error', 'message': stderr}

    lines = readFile('/usr/src/output/autogenerated.py')

    return {'code': 'success', 'message': lines}


@app.route("/read")
def read_result():
    lines = readFile('/usr/src/output/test.txt')

    return {'result': lines}


@app.route("/execute")
def execute():
    with open('/usr/src/output/test.txt', 'w') as f:
        process = subprocess.Popen(
            ['python', '/usr/src/output/autogenerated.py'], stdout=f,
            stderr=subprocess.PIPE, universal_newlines=True)

    stdoutp, stderrp = process.communicate()

    if(stderrp):
        return {'code': 'error', 'message': stderrp}

    return {'code': 'success'}


def readFile(dir):
    lines = []
    with open(dir, 'r', encoding='UTF-8') as file:
        lines = file.read()
    return lines
