package drawflow

import (
	"log"
	"os"
)

func WriteFile(code string) error {
	err := os.WriteFile("/usr/src/output/autogenerated.py", []byte(code), 0666)
	if err != nil {
		log.Print(err)
	}

	return err
}
